### PR TITLE
fix header issues

### PR DESCRIPTION
**Pull request by amy-baker**

### CODE REVIEW

**Comment by nearhanfarhan** [comment]
@amy-baker issue on home page where map is tiny and no tracking button 
Screenshot_20230926-173002

**Comment by nearhanfarhan** [comment]
Also having issues with the google maps autocorrect - I can search for locations but I can't select them, either on the home page or on destinations

**Comment by nearhanfarhan** [comment]
Also autocorrect box gets cut off by this component 
Screenshot_20230926-173428

**Comment by ccdu1010** [comment]
The above problem has been tidy up on this branch, works fine with Android emulator, ready to review.

**Pull request merged**
